### ISSUE TITLE
Seal encryption is inconsistent with JS implementation

### ISSUE THREAD

**Issue by armaniferrante** [oasislabs/deoxysii-rust#15]
Rust
```
    fn encrypt_something() {
        let plaintext = vec![0];
        let nonce = [0u8; 15];
        let symmetric_key = [10, 213, 217, 89, 194, 115, 57, 183, 253, 138, 189, 242, 51, 198, 244, 192, 19, 63, 91, 24, 197, 177, 66, 87, 110, 208, 215, 188, 61, 99, 193, 238];
        let d2 = deoxysii::DeoxysII::new(&symmetric_key);
        let r = d2.seal(&nonce, plaintext, vec![]);
        println!("{:?}", r);
    }
```

Outputs: `[46, 168, 87, 159, 53, 35, 156, 67, 169, 207, 65, 189, 8, 122, 206, 71, 230]`

JavaScript
```
  function encryptSomething() {
	let plaintext = new Uint8Array([0]);
	let nonce = new Array(15).fill(0);
	let symKey = new Uint8Array([10, 213, 217, 89, 194, 115, 57, 183, 253, 138, 189, 242, 51, 198, 244, 192, 19, 63, 91, 24, 197, 177, 66, 87, 110, 208, 215, 188, 61, 99, 193, 238]);
	let d2 = new deoxysii.AEAD(symKey);
	let encryption = d2.encrypt(nonce, plaintext, new Uint8Array([]));
	console.log("", encryption);
}
```

Outputs: `Uint8Array([[84, 28, 78, 228, 248, 107, 218, 104, 110, 135, 55, 55, 174, 35, 31, 240, 157]])`

**Comment by kostko** [comment]
Don't we validate all implementations against the same test vectors?

**Comment by Yawning** [comment]
> Don't we validate all implementations against the same test vectors?

Yes.

**Comment by Yawning** [comment]
The inconsistency appears to be with the JS implementation, since the Rust output matches what is produced by `github.com.oasislabs/deoxysii`.  I'm going to move this there, though I suspect that this is probably something silly like, using a version of the JS code that pre-dates the bump to v1.43 of the spec.

**Comment by Yawning** [comment]
Using `master` of `github.com/oasislabs/deoxysii.js` produces:
`Uint8Array [ 46, 168, 87, 159, 53, 35, 156, 67, 169, 207, 65, 189, 8, 122, 206, 71, 230 ]`

![Human error](https://pics.me.me/it-can-only-be-attributable-to-human-error-14557724.png)

**Comment by armaniferrante** [comment]
Thanks @Yawning. Can confirm I was using deoxyss.js 0.0.1. Upgrading to 0.0.2 fixes the problem.
